language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r conf/requirements.txt
  - pip install -r conf/requirements_test.txt
# command to run tests
script:
  - pytest app/test_certificate_checker.py
