global:
    # How frequently to scrape targets by default.
    scrape_interval: 10s
    # How long until a scrape request times out.
    scrape_timeout: 5s
    external_labels:
        monitor: 'ssl-chertificate-check'

scrape_configs:
    #- job_name: 'prometheus'
    #  static_configs:
    #      - targets: ['localhost:9090']
    - job_name: 'SSL-certificate-metrics'
      scrape_interval: 10s
      static_configs:
          - targets: ['172.17.0.1:8000']